language: cpp
dist: bionic
compiler: gcc
sudo: required

services:
  - xvfb

addons:
  # Boost
  apt: 
    packages: libboost-all-dev


install: 
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  - sudo apt-get install -qq libqt5svg5-dev
  # Qwt
  - sudo apt-get install -qq libqwt-qt5-dev
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # Codecov
  - sudo pip install codecov
  # SLOCcount
  - sudo apt-get install sloccount
  # OCLint
  - ./install_oclint.sh

script: 
  - ./download_other_githubs.sh
  - ./build_other_githubs.sh
  # Console test
  - qmake -qt=qt5 korter_project_console_test.pro
  - make debug --silent
  - ./korter_project_console_test
  # Desktop
  - qmake -qt=qt5 korter_project_desktop.pro
  - make --silent
  #- ./korter_project_desktop &
  #- sleep 10
  #- sudo killall -9 korter_project_desktop
  # cppcheck, be mild
  - cppcheck --quiet --error-exitcode=0 . 
  #- cppcheck --quiet --error-exitcode=1 . 
  # Call OCLint
  - ./do_oclint | true
  # Get code coverage
  - ./get_code_cov.sh >/dev/null
  - codecov >/dev/null
  # SLOCcount, destructive
  - rm -rf oclint-0.10.3
  - rm -rf pics
  - rm -rf .git
  - rm -rf debug
  - rm -rf release
  - cd ..; sloccount --overhead 1 --personcost 22614 korter_project; cd korter_project

after_success:
  - bash <(curl -s https://codecov.io/bash)
